[package]
name = "kernox"
description = "A high-performance composable application kernel for Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
serverless = ["dep:kernox-host-serverless"]
tokio = ["dep:kernox-host-tokio"]
full = ["serverless", "tokio"]

[dependencies]
kernox-core.workspace = true
kernox-host-serverless = { path = "../kernox-host-serverless", version = "1.0.0", optional = true }
kernox-host-tokio = { path = "../kernox-host-tokio", version = "1.0.0", optional = true }
kernox-runtime = { path = "../kernox-runtime", version = "1.0.0" }

[lints]
workspace = true
